import type { Metadata } from 'next'
import Link from 'next/link'
import { ChevronLeft, Lock, EyeOff, Users, X } from 'lucide-react'
import { VerifiedMark } from '@/components/brand/VerifiedMark'
import { SiteFooter } from '@/components/site/SiteFooter'
import { ShareButton } from '@/components/site/ShareButton'
import { human as humanDuration, clock } from '@/lib/duration'
import {
  analyzeSession, qualityOf, reflectionFor, type AttentionEvent,
} from '@/lib/behavior'

// SatyaShift — /demo: the proof before the ask.
//
// A skeptical visitor's one objection is "I'm not installing another extension that
// watches my browsing." This page answers it the only way that works: by SHOWING a
// finished session — the reflection AND the complete underlying record — with no
// account, no email, no cookie banner between them and the truth.
//
// Honesty rule: the Satya line below is not marketing copy. The sample events are
// fed through the real lib/behavior.ts engine at render time — the same pure code
// that analyzes every production session. If the engine changes, this page changes.

export const metadata: Metadata = {
  title: 'See a session — SatyaShift demo',
  description:
    'A real focus session, exactly as SatyaShift sees it: the honest reflection, and the complete domain-only record behind it. No account needed.',
  alternates: { canonical: '/demo' },
  openGraph: {
    title: 'See a session — SatyaShift demo',
    description: 'The reflection, and the complete domain-only record behind it. No account needed.',
    url: '/demo',
    siteName: 'SatyaShift',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'See a session — SatyaShift demo',
    description: 'The reflection, and the complete domain-only record behind it. No account needed.',
  },
}

// One realistic afternoon of thesis writing: a strong start, one distraction loop
// (youtube → x → back to youtube), and a long clean return. 2:05–4:18 PM.
const SAMPLE: AttentionEvent[] = [
  { domain: 'scholar.google.com', category: 'neutral', duration_s: 9 * 60 },
  { domain: 'docs.google.com', category: 'productive', duration_s: 38 * 60 },
  { domain: 'en.wikipedia.org', category: 'neutral', duration_s: 12 * 60 },
  { domain: 'docs.google.com', category: 'productive', duration_s: 21 * 60 },
  { domain: 'youtube.com', category: 'distraction', duration_s: 4 * 60 },
  { domain: 'x.com', category: 'distraction', duration_s: 3 * 60 },
  { domain: 'youtube.com', category: 'distraction', duration_s: 5 * 60 },
  { domain: 'docs.google.com', category: 'productive', duration_s: 41 * 60 },
]

export default function DemoPage() {
  // The real engine, at render time. Nothing on this page is hand-written praise.
  const signals = analyzeSession(SAMPLE)
  const quality = qualityOf(signals)
  const satyaLine = reflectionFor(signals, signals.total_s)

  // Per-domain rollup, same derivation as the session page's private view.
  const perDomain = (() => {
    const map = new Map<string, { total: number; drift: number }>()
    for (const e of SAMPLE) {
      const cur = map.get(e.domain) ?? { total: 0, drift: 0 }
      cur.total += e.duration_s
      if (e.category === 'distraction') cur.drift += e.duration_s
      map.set(e.domain, cur)
    }
    return [...map.entries()]
      .map(([domain, v]) => ({ domain, seconds: v.total, drift: v.drift > v.total - v.drift }))
      .sort((a, b) => b.seconds - a.seconds)
  })()

  return (
    <main className="min-h-screen bg-paper text-ink">
      <div className="mx-auto max-w-2xl px-6 py-12">
        <Link href="/" className="mb-8 inline-flex items-center gap-1.5 text-sm font-medium text-faint transition-colors hover:text-ink">
          <ChevronLeft className="h-4 w-4" /> SatyaShift
        </Link>

        <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-faint">A finished session &middot; sample data</p>
        <h1 className="mt-2 font-serif text-[2rem] leading-tight tracking-[-0.01em] text-ink">
          This is everything SatyaShift sees.
        </h1>
        <p className="mt-3 text-[15px] leading-relaxed text-soft">
          Below is one afternoon of thesis writing, exactly as the product records and
          reflects it. The reflection is generated by the same code that runs on real
          sessions — and the table at the bottom is the <span className="font-medium text-ink">complete</span> record.
        </p>

        {/* The session, as its owner sees it */}
        <div className="mt-8 rounded-xl border border-green-line bg-green-tint p-6">
          <div className="mb-4 flex flex-wrap gap-2">
            <span className="inline-flex items-center gap-1.5 rounded-full bg-green px-3 py-1 text-xs font-semibold text-white">
              <VerifiedMark verified size={13} className="text-white" /> Extension verified
            </span>
          </div>
          <div className="flex flex-wrap items-end justify-between gap-3">
            <div>
              <h2 className="font-serif text-[1.6rem] leading-tight text-ink">Thesis, chapter two</h2>
              <p className="mt-1.5 font-mono text-xs text-green">2:05pm &ndash; 4:18pm &middot; one afternoon</p>
            </div>
            <div className="text-right leading-none">
              <div className="font-mono text-[2.4rem] font-medium text-green-deep">{humanDuration(signals.total_s)}</div>
              <div className="mt-1 text-xs text-green">of verified focus</div>
            </div>
          </div>
        </div>

        {/* Where the time went — the owner's private view */}
        <div className="mt-6 rounded-xl border border-line bg-card p-4">
          <div className="mb-1 flex items-center gap-1.5">
            <Lock className="h-3.5 w-3.5 text-ghost" />
            <span className="font-mono text-[11px] uppercase tracking-[0.14em] text-faint">Private &middot; only the owner sees this</span>
          </div>
          {perDomain.map((row) => (
            <div key={row.domain} className="flex items-center justify-between border-b border-hairline py-2 last:border-0">
              <span className="font-mono text-[13px] text-ink">{row.domain}</span>
              <span className="flex items-center gap-2.5">
                <span className="font-mono text-[13px] text-faint">{clock(row.seconds)}</span>
                {row.drift ? (
                  <span className="rounded-full bg-clay-tint px-2 py-0.5 font-mono text-[11px] uppercase tracking-wide text-clay">drift</span>
                ) : (
                  <span className="rounded-full bg-green-tint px-2 py-0.5 font-mono text-[11px] uppercase tracking-wide text-green">focused</span>
                )}
              </span>
            </div>
          ))}
          <div className="mt-3 flex items-center justify-between border-t border-hairline pt-3">
            <span className="text-xs text-faint">Quality &middot; owner&rsquo;s eyes only</span>
            <span className="font-mono text-[13px] capitalize text-soft">{quality}</span>
          </div>
        </div>

        {/* The honest voice — computed, not copywritten */}
        <div className="mt-6 border-l-2 border-green pl-4">
          <div className="mb-1 font-mono text-[11px] uppercase tracking-[0.14em] text-green">Satya</div>
          <p className="font-serif text-[1.2rem] italic leading-snug text-ink">{satyaLine}</p>
          <p className="mt-2 text-xs leading-relaxed text-faint">
            This sentence was written by the analysis engine just now, from the events above —
            from the shape of the session, not a score. A different afternoon gets a different truth.
          </p>
        </div>

        {/* What a friend would see */}
        <div className="mt-8 rounded-xl border border-line bg-card p-4">
          <div className="mb-3 flex items-center gap-1.5">
            <Users className="h-3.5 w-3.5 text-green" />
            <span className="font-mono text-[11px] uppercase tracking-[0.14em] text-green">What a friend in your circle sees</span>
          </div>
          <div className="flex items-center gap-3">
            <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-green text-[13px] font-semibold text-white">A</span>
            <div className="min-w-0 flex-1">
              <p className="text-sm font-medium text-ink">Anaya</p>
              <p className="truncate text-xs text-faint">&ldquo;Thesis, chapter two&rdquo;</p>
            </div>
            <span className="inline-flex items-center gap-1.5 font-mono text-sm text-green">
              <VerifiedMark verified size={14} /> {humanDuration(signals.total_s)}
            </span>
          </div>
          <p className="mt-3 border-t border-hairline pt-3 text-xs leading-relaxed text-faint">
            Verified time and her own words. Never the sites, never the drift, never the quality.
          </p>
        </div>

        {/* The complete record — the trust argument, made literal */}
        <div className="mt-8">
          <h2 className="font-serif text-[1.4rem] text-ink">The complete record</h2>
          <p className="mt-2 text-[14px] leading-relaxed text-soft">
            Everything above was derived from the rows below. This table is not a summary —
            it is the <span className="font-medium text-ink">entire</span> raw record of the session.
            If our database leaked tomorrow, this is all anyone would learn about it.
          </p>
          <div className="mt-4 overflow-hidden rounded-xl border border-line bg-card">
            <div className="grid grid-cols-3 gap-2 border-b border-line bg-paper px-4 py-2 font-mono text-[11px] uppercase tracking-[0.14em] text-faint">
              <span>domain</span><span className="text-right">seconds</span><span className="text-right">category</span>
            </div>
            {SAMPLE.map((e, i) => (
              <div key={i} className="grid grid-cols-3 gap-2 border-b border-hairline px-4 py-1.5 font-mono text-[12px] last:border-0">
                <span className="text-ink">{e.domain}</span>
                <span className="text-right text-soft">{e.duration_s}</span>
                <span className="text-right text-faint">{e.category}</span>
              </div>
            ))}
          </div>
          <div className="mt-4">
            <div className="mb-2 flex items-center gap-1.5 font-mono text-[11px] uppercase tracking-[0.14em] text-faint">
              <EyeOff className="h-3 w-3" /> What does not exist, anywhere
            </div>
            {[
              'The pages, videos, or documents behind those domains',
              'Page titles, searches, messages, or anything typed',
              'Screenshots, history, or the other open tabs',
            ].map((t) => (
              <div key={t} className="flex items-center gap-2 py-0.5 text-[13px] text-faint">
                <X className="h-3.5 w-3.5 shrink-0 text-ghost" /> {t}
              </div>
            ))}
            <p className="mt-3 text-[13px] leading-relaxed text-soft">
              Not &ldquo;we don&rsquo;t look at it&rdquo; — it is never collected, so it cannot
              be stored, sold, subpoenaed, or leaked.{' '}
              <Link href="/privacy" className="font-medium text-ink underline decoration-line underline-offset-4 transition-colors hover:decoration-ink">
                The full promise
              </Link>
              .
            </p>
          </div>
        </div>

        {/* The ask, after the proof */}
        <div className="mt-10 flex flex-col gap-3 sm:flex-row">
          <Link
            href="/signup"
            className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-green px-6 py-3.5 text-sm font-semibold text-white transition-colors hover:bg-green-deep"
          >
            Start focusing — free
          </Link>
          <Link
            href="/how-it-works"
            className="flex items-center justify-center gap-2 rounded-lg border border-line bg-card px-6 py-3.5 text-sm font-semibold text-ink transition-colors hover:bg-green-wash"
          >
            How it works
          </Link>
        </div>

        {/* The honest growth loop: proof is meant to be shown. Placed AFTER the proof, where
            conviction peaks — a quiet invitation, never the page's green action. Shares the
            canonical demo link, so whoever receives it lands on this same proof, no account. */}
        <div className="mt-8 border-t border-hairline pt-6 text-center">
          <p className="text-[14px] leading-relaxed text-soft">
            Know someone who wants their focus to be real, not performed?
          </p>
          <ShareButton
            url="https://satyashift.com/demo"
            title="SatyaShift — Proof you did the work"
            text="See exactly what it tracks: a whole focus session, and the complete record behind it. No account needed."
            label="Show a friend"
            className="mt-3"
          />
        </div>
      </div>
      <SiteFooter />
    </main>
  )
}
